[project]
name = "games-project-lazarenko"
version = "0.1.0"
description = "вд-1"
authors = [
    { name = "Arseniy Lazarenko", email = "sasha9299836-rgb@gmail.com" },
]
dependencies = []
readme = "README.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
games-app = "games_project_lazarenko.scripts.main:main"
